# ~/.bash_profile
[[ -f ~/.bashrc ]] && . ~/.bashrc

# If we are on TTY1 and not in a GUI yet, jump straight into Sway
if [[ -z "$DISPLAY" ]] && [[ -z "$WAYLAND_DISPLAY" ]] && [[ "$(tty)" = "/dev/tty1" ]]; then
    exec sway
fi
